"""Backend package for application services."""

from __future__ import annotations

from .services import (
    DEFAULT_FIXTURE_PATH,
    ExcuseAPI,
    ExcuseSeedConfig,
    ExcuseSeedError,
    ExcuseService,
    InMemoryMemesRepository,
    LocalStorageService,
    MemeCreator,
    MemeRecord,
    MemesFilter,
    MemesQueryParams,
    MemesService,
    PaginatedMemes,
    Pagination,
    RandomMemeCache,
    SQLAlchemyMemesRepository,
    S3StorageService,
    StorageConfig,
    StorageService,
    auth_app,
    create_excuse_app,
    create_memes_app,
    get_excuse_service,
    get_memes_service,
    get_session_manager,
    get_storage_service,
    get_user_repository,
    require_admin_user,
    require_authenticated_user,
    reset_auth_state,
    session_manager,
    user_repository,
)

__all__ = [
    "ExcuseAPI",
    "ExcuseSeedConfig",
    "ExcuseSeedError",
    "ExcuseService",
    "DEFAULT_FIXTURE_PATH",
    "create_excuse_app",
    "get_excuse_service",
    "MemesService",
    "MemesFilter",
    "MemesQueryParams",
    "MemeRecord",
    "MemeCreator",
    "RandomMemeCache",
    "PaginatedMemes",
    "Pagination",
    "InMemoryMemesRepository",
    "SQLAlchemyMemesRepository",
    "create_memes_app",
    "get_memes_service",
    "StorageConfig",
    "StorageService",
    "LocalStorageService",
    "S3StorageService",
    "get_storage_service",
    "auth_app",
    "user_repository",
    "session_manager",
    "get_user_repository",
    "get_session_manager",
    "reset_auth_state",
    "require_authenticated_user",
    "require_admin_user",
]
